### ISSUE TITLE
Audio Output

### ISSUE THREAD

**Issue by stevespaw** [MindStudioOfficial/ndiscopes#4]
It starts to play audio, but locks up the app and crashes. :-( .

Is it possible to use PortAudio? I know that it is used in Ardour and Mixbus, (which I use) and is super stable and can also support ASIO.
http://files.portaudio.com/docs/v19-doxydocs/tutorial_start.html

I am not a developer, but just thought I would ask.
ASIO would allow Multichannel output to Dante :-).

Thanks, great potential here.
http://www.portaudio.com/apps.html

**Comment by MindStudioOfficial** [comment]
What do you use as Auifo source?

I have tested it with stereo audio from Screen Capture and 4 channel audio from NDI Test Patterns.

**Comment by MindStudioOfficial** [comment]
I first tried PortAudio but ran into threadibg limitations. Thats why I switched to libao.

**Comment by MindStudioOfficial** [comment]
@stevespaw can you reproduce the crash with any ither source that I could have access to? That way I could test it myself and fix the issue.

**Comment by stevespaw** [comment]
Doing some other testing with other PC's now to see if it may be an issue with my main PC which has a million things going on. :-). I will keep you posted

**Comment by MindStudioOfficial** [comment]
Weirdly I cannot reproduce the memory leak on the computer where I develop so I can't debug this. The leak appeared at work while using NDIscopes in conjunction with an Egato Camlink 4K and a BMD SDI to HDM Converter. Since I don't have a Camlink at home I cannot test whether it has to do anything with the hardware but that would not make any sense to me.

@stevespaw can you descripe the exact configuration you were using when the rash occured? (Number of Audiochannels, Video Resolution, ...) This would be very helpful.

**Comment by stevespaw** [comment]
Hey, sorry I just got back to this.  I have had no issues with the build. Had it running for several days on one machine. running it on my laptop now, no issues, mem hovers at 250 MB. I had NDI network issues on the PC that crashed the app. I do wish I could select the audio output like in VLC. But I can route with other tools now. This is great, Thanks!

**Comment by stevespaw** [comment]
Oops spoke to soon, after switching NDI inputs a few times - RAM use jumped to 1.8 GB !!!

**Comment by stevespaw** [comment]
OK, If I have VLC as an NDI source playing - RAM soars.... If that helps

**Comment by MindStudioOfficial** [comment]
@stevespaw thanks for getting back to me with you information. I've been testing the issue in the meantime myself and fount that the main thread that renders the user interface gets overwhelmed with the amount of incoming NDI frames when the GPU is under load from another software running on the machine. 

I've fixed this Issue by sending a "pause" message to the NDI thread that lets the main thread render the interface without getting flooded with new data. This also has the effect that if performance is low frames are dropped rather than put in a queue that fills up memory.

Luckily this was not a memory leak, so memory wasn't lost mitigating the risk of having to reboot the whole computer.

**Comment by MindStudioOfficial** [comment]
@stevespaw Just added the functionality to select audio devices. Will be in the next release (v0.6.0).
