### ISSUE TITLE
Startup failure on Windows 10 LTSB 1607

### ISSUE THREAD

**Issue by GralfR** [MindStudioOfficial/ndiscopes#4]
**Describe the bug**
Running 0.7.1-beta on Win10 just crashes. 
![debug](https://user-images.githubusercontent.com/66326427/191204601-e9bf2590-da7a-4808-8913-0cbf88ea9d5a.png)

**To Reproduce**
1. Download [0.7.1-beta](https://github.com/MindStudioOfficial/ndiscopes/releases/download/v0.7.1-beta/ndiscopes_windows_v0.7.1-beta.zip)
2. unzip all files to c:/ndiscopes
3. start ndiscopes.exe
4. just a messagebox, that says, the program does not work. The offered debug options shows the attached screenshot.

**Expected behavior**
Program starts fine

**Hardware/Software**
- Version of Windows: 10 LTSB 1607
- GPU Type/Manufacturer: NVIDIA GTX 1080 Ti
- NVIDIA-Driver 472.84
- NDI Tools 5.5
- NDI SDK installed

**Additional context**
Please no comments about "old Windows", "update drivers" etc. In general any program has to give proper error messages, if system requirements do not match and what is the problem. I think ll the systemrequirements are fullfilled. So what's the problem?

**Comment by MindStudioOfficial** [comment]
Hi,
Thanks for reporting this crash.
I believe your NVIDIA drivers are very outdated. The oldest supported driver version might be 511.xx.

If the error persists after updating your drivers feel free to post another comment in this thread.

Please let me know if this fix works so I can mark this Issue as closed. 

Thanks for using NDIScopes :D

**Comment by MindStudioOfficial** [comment]
Since I am a single person (student) developing this software I sadly do not have the resources to test a lot of driver/os/hardware configuarations. I will add the minimum required driver version to the README. I've checked again in the code and the minimum driver version is 511.23 to be exact. This is a limitation imposed by the CUDA library that Is only backwards compatible to a certain point. 

The error you describe never occuree in my testing, so I cold not yet implement a custom error message stating that your driver version is outdated.

**Comment by GralfR** [comment]
Hi!
Thanks for the quick response! Great support.
I tried to update my NVIDIA-driver to 516 but I can't find one that supports my system (desktop).
So I tried my laptop with Win10 pro 1909 and NVIDIA GTX1070 with mobile-driver 452.06.
On this system your app starts and works. It shows a NDI stream and all the scopes.

So, the old NVIDIA-driver was not the problem. Very strange, because as You said the CUDA requires this.
Maybe it's the old Win10 or because it's Win10 Enterprise or the system has NDI SDK installed (which the laptop has not)...?

What other information do You need to define a more detailed minimum requirements?

**Comment by MindStudioOfficial** [comment]
I didn't quite realise that you are using such an old version of Windows. The NDI SDK is not needed to run NDIScopes.
I researched further into your provided error message which might not actually have anything to do with CUDA or the GPU afterall. It generally seems to be an access violation mainly caused by a corrupted exe or an incompatible OS. 
So I am guessing you are right regarding the old Windows version. 

I did the CUDA part a long time ago and the minimum driver version I mentioned might have applied before I compiled the CUDA part for older GPUs aswell. So that might be the reason why It works on older drivers and probably why I didn't mention a driver version in the README.

I will try to find out what exactly causes the crash. Then I can maybe find incompatibilities and define better minimun requirements. 

Is the original system 64Bit or 32Bit?

**Comment by GralfR** [comment]
All my systems are 64bit on Intel CPU. The desktop has a i7-8700K, the laptop a i7-6820HK.

**Comment by MindStudioOfficial** [comment]
Thanks for the detailed information. I will investigate that issue further.

**Comment by GralfR** [comment]
I tried another system with i3-3110M CPU and only internal Intel HD4000 graphics, no NVIDIA. This system runs Win10 pro 2004.
NDIscopes starts on this system and finds NDI-sources, but does not show any scopes, only meta-data, which is right, because of missing CUDA.
Maybe, the app should recognize this (no NVIDIA-card) and show this (and maybe other system requirements not met) to the user so one does not struggle using this software and some parts do not work.

**Comment by MindStudioOfficial** [comment]
I already have implemented a check for the GPU... but apparently that doesn't work. Thanks for letting me know.

**Comment by MindStudioOfficial** [comment]
Fixed the GPU check and tested it on my laptop (No GPU).

![grafik](https://user-images.githubusercontent.com/62838401/191256135-1a30477f-7ec9-422b-92ec-6abac3f7981f.png)

**Comment by GralfR** [comment]
Okay.
But with #5 in mind, it might be worth to have at least the working source-selector and meta-data available and just this error-message on all scopes  and/or all scopes disabled and off with a messagebox-popup of this error if the user tries to open a not supported feature.

**Comment by MindStudioOfficial** [comment]
To be honest... in this case I would make a seperate software like "NDIExplorer" that does just that and runs on even more hardware.

**Comment by GralfR** [comment]
release 0.7.2 beta is running on the Windows 10 LTSB 1607 now. Thanks for the fix.
The CUDA-detection seams to work. Program displays the error on a system with NVIDIA GTX460 HAWK.

**Comment by MindStudioOfficial** [comment]
Thanks for testing 👍
