### ISSUE TITLE
display RAW stream data

### ISSUE THREAD

**Issue by GralfR** [MindStudioOfficial/ndiscopes#5]
**Is your feature request related to a problem? Please describe.**
I'm looking for a tool that helps debugging NDI problems in general. The Newtek NDI-Tools do not offer all technical informations about a stream. The NDI Analysis is even hard to operate as a commandline-tool and does not show a lot of information, e.g. nothing about the colorformat.

**Describe the solution you'd like**
Because your tool already has analysing tools for the audio/video I think it would be easy to add some kind of debug- or raw-data display. I'd like to have all informations about a NDI-stream to be able to find any issue that might be the reason for compatibility-problems. These data should be:

- NDI version of the stream
- Source-IP
- NIC of the system that is used (i.e. the source is found on)
- network protocol (unicast TCP or multicast etc.)
- NDI groupname
- video resolution (width x height)
- framerate and format (e.g. 60fps progressive)
- colorformat (e.g. RGB or UVYV or 422 etc.)
- videocodec (full NDI or NDI|HX / h.264, h.265 ...)
- alpha-channel?
- bitrate
- number of audio channels
- audio-codec
- audio-level
- ...

**Describe alternatives you've considered**
Newtek NDI Analysis only has video resolution, nothing about colorformat, and is a commandline-tool, which needs a lot of typing to find a source and read the data.
Birddog DYNO can display the colorformat, but has problems connecting to the right network interface and thus does not find the stream if more than one NIC is active on your system.
Searched github and the web, but nothing found.
Tried to code a tool myself, but Newtek SDK does not support my old Visual Basic Express 2010.

**Additional context**
There does not have to be a big GUI fo this. A list or table is enough. I expected this shown in the "meta data"-area of ndiscopes, but it doesn't.
Because I'm connecting and converting several sources (PC with HDMI 1080p60, HDMI-NDI-Encoder, SDI-NDI-Encoder, Android- and iOS-Apps, different Windows-Apps) I'd like to monitor the NDI-world and make sure, I get the best quality, lowest latency without up/down/cross-convertion on any device if not needed, and investigate incompatibilities. The Newtek NDI-tools can't do this.

**Comment by MindStudioOfficial** [comment]
Thanks for posting this feature request.
1. Your proposal sounds great and I am considering implementing this.
2. Some of the data you require is already displayed in different parts of the UI but I understand that having the data grouped/sorted in one place is preferable.
3. Some of the things you requested might not be accessible through the NDI SDK.
4. Something like videocodec is probably dependant on what the receiver is capable of (Conversion from Full NDI to HX and vice versa happen in the background and is not visible through the SDK as far as I know.
5. The Metadata tab shows XML based metadata sent as seperate metadata frames by the sender. This can be seen when using NDI ScreenCapture as a source since it sends metadata along with the video. But adding a table of data to this tab might even make it more useful.

Thank you for proposing such a detailed feature. If you have any more ideas on data that should be shown please add them in this thread. I will keep you updated on the progress of the feature development.

**Comment by GralfR** [comment]
Thank you for considering to add this feature.
All the data I wrote in the list were things that came into my mind playing with NDI on different systems (Windows, Linux, Android, iOS, Hardware Dual en/decodes) and struggling to get streams connected. So, if any item is not supported yet by the SDK, that's ok. If any other property is available via the SDK or any other function in the software, it might become usefull in the future, too. Just dump all the arrays You have for a first implementation ;-) and then I'll take a look, what is missing...

**Comment by MindStudioOfficial** [comment]
I will try to implement as much as possible.
This will of course take some time.

**Comment by MindStudioOfficial** [comment]
A first look:
- Colors indicate different datatypes
- Values are selectable to be copied as needed
![grafik](https://user-images.githubusercontent.com/62838401/191281311-3eaf392d-f9be-44a7-a588-b7f4f45754ce.png)

**Comment by MindStudioOfficial** [comment]
Currently Implemented in v0.7.2-beta
  - Source Name
  - Source IP Address
  - Resolution
  - Framerate
  - Aspect Ratio
  - FourCC
  
I don't really have access to more data since things like compression or video codec are handled internally by the NDI SDK.
